### ISSUE TITLE
tokudb_version is null

### ISSUE THREAD

**Issue by alexeyz** [Tokutek/mariadb-5.5#10]
In version 5.5.30-tokudb-7.0.4-MariaDB-log:

MariaDB [(none)]> show variables like 'tokudb_version';
+----------------+-------+
| Variable_name  | Value |
+----------------+-------+
| tokudb_version |       |
+----------------+-------+
1 row in set (0.00 sec)

This was not the case with earlier engines.

**Comment by prohaska** [comment]
this is fixed on the ft-engine master and scheduled for tokudb 7.0.5
