### ISSUE TITLE
Warnings "Could not remove temporary table" on disconnect with a temporary table after a ROLLBACK

### ISSUE THREAD

**Issue by elenst** [Tokutek/mariadb-5.5#26]
The following set of commands causes a warning in server error log after the connection disconnects:

DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (a INT, b INT) ENGINE=TokuDB;
BEGIN;
SELECT b FROM t1;
CREATE TEMPORARY TABLE tmp1 ( i INT ) ENGINE=TokuDB SELECT b FROM t1;
ROLLBACK;

The warning comes in different flavors. 
With 
SET GLOBAL log_output='TABLE';
SET GLOBAL general_log = ON;

131209  3:32:56 [Warning] Could not remove temporary table: '/home/elenst/bzr/10.0/data/tmp/#sql6b52_e_0', error: 175

With
SET GLOBAL log_output='FILE';

131209  3:34:13 [Warning] Could not remove temporary table: '/home/elenst/bzr/10.0/data/tmp/#sql6b52_f_0', error: 2

Reproducible on mariadb-5.5.30-tokudb-7.0.1 and mysql-5.5.30-tokudb-7.0.1. 

I'm not sure whether it's related to #25 , since it doesn't contain details.

**Comment by tmcallaghan** [comment]
Moved to Jira as https://tokutek.atlassian.net/browse/DB-565
