### ISSUE TITLE
ICP desc bug

### ISSUE THREAD

**Issue by prohaska** [Tokutek/mariadb-5.5#39]
I've (Zardosht) noticed a scenario with index condition pushdown (ICP) in MariaDB
that leads to really bad performance in TokuDB. I don't know if it is
a bug in ICP or if TokuDB is misusing/misunderstanding the API.

Here is the problem. Suppose we run the following query on the following schema:

```
SELECT * FROM foo WHERE col1 = '7' ORDER BY b desc

| foo   | CREATE TABLE `foo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `col1` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `b` int(11) DEFAULT NULL,
  `c` int(11) DEFAULT NULL,
  `d` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  CLUSTERING KEY `col1_2` (`col1`,`b`)
) ENGINE=TokuDB AUTO_INCREMENT=8001 DEFAULT CHARSET=utf8
COLLATE=utf8_unicode_ci ROW_FORMAT=TOKUDB_ZLIB |
```

The output of explain is:

```
MariaDB [test]> explain SELECT * FROM foo WHERE col1 = '7' ORDER BY b desc;
+------+-------------+-------+------+---------------+--------+---------+-------+------+-------------+
| id   | select_type | table | type | possible_keys | key    | key_len
| ref   | rows | Extra       |
+------+-------------+-------+------+---------------+--------+---------+-------+------+-------------+
|    1 | SIMPLE      | foo   | ref  | col1_2        | col1_2 | 302
| const | 1320 | Using where |
+------+-------------+-------+------+---------------+--------+---------+-------+------+-------------+
1 row in set (2.32 sec)
```

The query is doing a reverse range scan, as it should.

We get handler::idx_cond_push called, but end_range is not set. As a
result, TokuDB thinks it can use index condition pushdown to filter
rows. As we do this and get to the end, because end_range is not set,
we never get a result of ICP_OUT_OF_RANGE, and always get a result of
ICP_NO_MATCH. So, when we go to retrieve that first row past the end
of the range, the row that will tell MySQL it should stop searching,
TokuDB never finds a row and never gets ICP_NO_MATCH. It scans to the
beginning of the index (because it is running in reverse order),
getting ICP_NO_MATCH for every row it encounters.

Although my index is clustering, I've seen this with a normal key as well.

If col1 is an int instead of the funky varchar, handler::idx_cond_push
is never called, so this problem does not exist.

It seems to me that if end_range is not set and we cannot reliably
learn when we go out of range, we should not have
handler::idx_cond_push called, otherwise we can get bad performance
such as the example above.

**Comment by prohaska** [comment]
To: Zardosht Kasheff zardosht@xxxxxxxxx
From: Sergei Petrunia psergey@xxxxxxxxxxxx
Date: Tue, 12 Mar 2013 00:56:40 +0400
Cc: maria-developers@xxxxxxxxxxxxxxxxxxx
In-reply-to: <CABFd+SFYNezSsmKJbCh3wMdP+u1cB_vgfW66h9FWER-aHzd2cQ@mail.gmail.com>
User-agent: Mutt/1.5.18 (2008-05-17)
Hi Zardosht,

On Thu, Mar 07, 2013 at 11:08:01PM -0500, Zardosht Kasheff wrote:

> I have found an interesting issue with index condition pushdown. I do
> not know if it is a bug, or if I am misusing the feature.
> 
> I have found that in one scenario, when performing a join, an index
> condition is pushed down, but because handler->end_range is not set,
> handler_index_cond_check never returns ICP_OUT_OF_RANGE, even though
> we are out of range.

Confirm. I have looked how it works in MyISAM and InnoDB. Indeed, they consider
scan over equality to be a special case. They remember the lookup key and
check it themselves.

That is, if one does

  h->index_read(key='foo')=0
  h->index_next_same()

then index_next_same() will check whether the next index tuple has key='foo'. 
If the key is different, it will return HA_ERR_END_OF_FILE without checking 
the index condition.

I'm hesitant to say that this is "by design", I'd say that the available 
storage engines happened to work this way, and then ICP used that.

Maybe, this means that implementation of handler::index_next_same() should
set handler::end_range. If it did, a storage engine will be able to support 
ICP without implementing index_next_same() call.

The question for MariaDB is, does it make sense for us to make this change in
MariaDB, when Oracle doesn't support it? 

(As far as I understand, TokuDB will still need to support MySQL, and so will
have to work around the problem by supporting index_next_same() and comparing
the keys like MyISAM/InnoDB do.  When you have to do that anyway, there is no 
benefit from having this problem fixed in MariaDB...)

> Here is the relevant stack trace, I cannot yet send the entire trace
> as it may include customer information, and I need to double check it
> is ok to send:
> <skip>
> 
> In this stack, we are performing an index_next_same, and a condition
> has been pushed down. When we call handler_index_cond_check. we always
> get ICP_NO_MATCH and never get ICP_OUT_OF_RANGE, even though we go
> past the key that we should be retrieving.
> 
> Is this by design? Is this a bug?
> 
> ## 
> 
> BR
> 
> ##  Sergei
> 
> Sergei Petrunia, Software Developer
> Monty Program AB, http://askmonty.org
> Blog: http://s.petrunia.net/blog

**Comment by willt** [comment]
I just ran into this bug when converting over to TokuDB.
Is there any ETA on a fix for this yet?

**Comment by tmcallaghan** [comment]
Moved to Jira as https://tokutek.atlassian.net/browse/DB-534
