### ISSUE TITLE
deb packages for tokutek-mariadb-5.5 builds

### ISSUE THREAD

**Issue by gituser** [Tokutek/mariadb-5.5#51]
is there any?

i noticed there is already packages for TokuMX - https://github.com/Tokutek/mongo/wiki/Installing-on-Debian-and-Ubuntu

any chance to make the same for MariaDB builds?

many thanks.

**Comment by joelaflamme** [comment]
There are currently no deb packages for TokuDB mariadb packages.

**Comment by gituser** [comment]
yes, that's correct.

I mean you're already building debian packages for TokuMX so why not to build for MariaDB tokuDB too?

**Comment by tmcallaghan** [comment]
Moved to Jira as https://tokutek.atlassian.net/browse/DB-561
