### ISSUE TITLE
OPTIMIZE TABLE command causes crash on locked table

### ISSUE THREAD

**Issue by joel9001** [Tokutek/mariadb-5.5#55]
This issue was identified during a sql-bench run of test-insert against mariadb-5.5.30-tokudb-7.1.0-debug-e-linux-x86_64.  A crash occurred after an optimize command was run against a locked table.

Here is an excerpt from the error log:

140417 10:59:36 [ERROR] mysqld got signal 11 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.

To report this bug, see http://kb.askmonty.org/en/reporting-bugs

We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed,
something is definitely wrong and this may fail.

Server version: 5.5.30-tokudb-7.1.0-debug-e-MariaDB-debug-log
key_buffer_size=134217728
read_buffer_size=131072
max_used_connections=1
max_threads=153
thread_count=1
It is possible that mysqld could use up to
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 466223 K  bytes of memory
Hope that's ok; if not, decrease some variables in the equation.

Thread pointer: 0x0x7fb833b87060
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
stack_bottom = 0x7fb8d5bb2de8 thread_stack 0x48000
mysys/stacktrace.c:246(my_print_stacktrace)[0xbb9458]
sql/signal_handler.cc:155(handle_fatal_signal)[0x7265dc]
??:0(??)[0x7fb8d5476bb0]
sql/sql_admin.cc:579(mysql_admin_table)[0x6a895d]
sql/sql_admin.cc:1085(Optimize_table_statement::execute(THD_))[0x6a9c04]
sql/sql_parse.cc:4493(mysql_execute_command(THD_))[0x5da006]
sql/sql_parse.cc:5774(mysql_parse(THD_, char_, unsigned int, Parser_state_))[0x5db43e]
sql/sql_parse.cc:1065(dispatch_command(enum_server_command, THD_, char_, unsigned int))[0x5dbede]
sql/sql_parse.cc:798(do_command(THD_))[0x5dd615]
sql/sql_connect.cc:1266(do_handle_one_connection(THD*))[0x69ca0e]
sql/sql_connect.cc:1183(handle_one_connection)[0x69cb00]
??:0(??)[0x7fb8d546ef6e]
??:0(??)[0x7fb8d47549cd]

Trying to get some variables.
Some pointers may be invalid and cause the dump to abort.
Query (0x7fb7fc840078): OPTIMIZE TABLE bench1
Connection ID (thread ID): 3034

**Comment by joel9001** [comment]
Additonally, this issue appears not to occur on mariadb-5.5.36-tokudb-7.1.5-debug-e-linux-x86_64 but may require additional investigation to fully understand how it may impact current releases.

**Comment by prohaska** [comment]
when the client locks the table, there is no need for hot optimize table.

```
lock tables t write
optimize table
```

with this case, and with temporary tables, do not try to downgrade the MDL.  this problem was fixed in 7.1.5: https://github.com/Tokutek/mysql-5.6/issues/46.
