### ISSUE TITLE
Dependency on GLIBCXX_3.4.15 breaks handlersocket on default RHEL6

### ISSUE THREAD

**Issue by thatsafunnyname** [Tokutek/mariadb-5.5#6]
Hello and thank you for TokuDB,

I also posted in the tokudb-user mailing list but just noticed that github is the place to report bugs.

On Red Hat Enterprise Linux Server release 6.X which has by default glibcxx 4.4 (glibc 2.12), when using mariadb-5.5.30-tokudb-7.0.1-linux-x86_64.tar.gz

INSTALL PLUGIN handlersocket SONAME 'handlersocket.so';
ERROR 1126 (HY000): Can't open shared library 'mariadb-5.5.30-tokudb-7.0.1-linux-x86_64/lib/plugin/handlersocket.so' (errno: 2 /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by mariadb-5.5.30-tokudb-7.0.1)

MariaDB have bintar downloads for GLIBC_2.14+ specifically - https://downloads.mariadb.org/mariadb/5.5.31/#os_group=linux_generic&file_type=tar_gz
The non GLIBC_2.14+ bintars from mariadb work on RHEL6 (including handlersocket) and I imagine on other OS versions with older versions of GLIBC(XX).  I think mariadb are building on an OS with an older version of GLIBC(XX).

ldd mariadb-5.5.30-tokudb-7.0.1-linux-x86_64/lib/plugin/handlersocket.so
mariadb-5.5.30-tokudb-7.0.1-linux-x86_64/lib/plugin/handlersocket.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by mariadb-5.5.30-tokudb-7.0.1-linux-x86_64/lib/plugin/handlersocket.so)
        linux-vdso.so.1 =>  (0x00007fff05a55000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007ff735986000)
        libm.so.6 => /lib64/libm.so.6 (0x00007ff735701000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ff735360000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003763e00000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ff73514a000)

readelf -d mariadb-5.5.30-tokudb-7.0.1-linux-x86_64/lib/plugin/handlersocket.so

Dynamic section at offset 0x24e08 contains 27 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [handlersocket.so]
 0x000000000000000c (INIT)               0xbac8
 0x000000000000000d (FINI)               0x20314
 0x0000000000000019 (INIT_ARRAY)         0x224600
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x224608
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x0000000000000004 (HASH)               0x158
 0x0000000000000005 (STRTAB)             0x3c10
 0x0000000000000006 (SYMTAB)             0xd48
 0x000000000000000a (STRSZ)              17768 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x225160
 0x0000000000000002 (PLTRELSZ)           5424 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0xa598
 0x0000000000000007 (RELA)               0x85d0
 0x0000000000000008 (RELASZ)             8136 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x8560
 0x000000006fffffff (VERNEEDNUM)         2
 0x000000006ffffff0 (VERSYM)             0x8178
 0x000000006ffffff9 (RELACOUNT)          81
 0x0000000000000000 (NULL)               0x0

ldd mariadb-5.5.31-linux-x86_64/lib/plugin/handlersocket.so
        linux-vdso.so.1 =>  (0x00007fff133ff000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fa468161000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fa467e5a000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fa467bd6000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fa467835000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003763e00000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fa46761e000)

readelf -d mariadb-5.5.31-linux-x86_64/lib/plugin/handlersocket.so

Dynamic section at offset 0x278e8 contains 25 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [handlersocket.so]
 0x000000000000000c (INIT)               0xb038
 0x000000000000000d (FINI)               0x22d58
 0x0000000000000004 (HASH)               0x158
 0x000000006ffffef5 (GNU_HASH)           0xc60
 0x0000000000000005 (STRTAB)             0x3f68
 0x0000000000000006 (SYMTAB)             0x1610
 0x000000000000000a (STRSZ)              15189 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x227c28
 0x0000000000000002 (PLTRELSZ)           4488 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x9eb0
 0x0000000000000007 (RELA)               0x7ed0
 0x0000000000000008 (RELASZ)             8160 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x7e30
 0x000000006fffffff (VERNEEDNUM)         3
 0x000000006ffffff0 (VERSYM)             0x7abe
 0x000000006ffffff9 (RELACOUNT)          80
 0x0000000000000000 (NULL)               0x0

rpm -qf /usr/lib64/libstdc++.so.6
libstdc++-4.4.6-3.el6.x86_64

strings /usr/lib64/libstdc++.so.6 | grep GLIBC
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBC_2.2.5
GLIBC_2.3
GLIBC_2.4
GLIBC_2.3.2
GLIBCXX_FORCE_NEW
GLIBCXX_DEBUG_MESSAGE_LENGTH

nm mariadb-5.5.30-tokudb-7.0.1-linux-x86_64/lib/plugin/handlersocket.so | grep 'GLIBCXX_3.4.15'
                 U _ZNSt8__detail15_List_node_base7_M_hookEPS0_@@GLIBCXX_3.4.15
                 U _ZNSt8__detail15_List_node_base9_M_unhookEv@@GLIBCXX_3.4.15

nm mariadb-5.5.31-linux-x86_64/lib/plugin/handlersocket.so | grep List_node_base
                 U _ZNSt15_List_node_base4hookEPS_@@GLIBCXX_3.4
                 U _ZNSt15_List_node_base6unhookEv@@GLIBCXX_3.4

Red Hat EL6 does not by default have version > 4.5 of libstdc++6 with GLIBCXX_3.4.15.

I did notice in https://github.com/Tokutek/ft-engine/blob/master/README.md that GCC >= 4.7 is recommended and that I will have to pass --cc and --cxx options as the default is 4.7.  I also noticed in https://github.com/Tokutek/ft-engine/issues/7#issuecomment-17050811 CentOS 5 is used with 4.7 installed because a C++11-compatible compiler is needed (http://gcc.gnu.org/gcc-4.7/cxx0x_status.html), and I can get these RPMs for EL(5|6) from devtools.  From what I have read it looks like building the mariadb src (with tokudb) on EL6 with the default GCC will not work, I imagine the mariadb buildbots would detect this.  Hmm, looks like I'll be trying GCC 4.7.2 from RH devtools:
https://access.redhat.com/site/documentation/en-US/Red_Hat_Developer_Toolset/1/html/1.1_Release_Notes/ch-Features.html 

Thanks again.

https://lists.launchpad.net/maria-developers/msg04821.html
https://bugs.launchpad.net/maria/+bug/1049621
http://www.sourceware.org/bugzilla/show_bug.cgi?id=12518

grep -A 5 '^VERSION' mariadb-5.5.30-tokudb-7.0.1-linux-x86_64/bin/mysqlbug
VERSION="5.5.30-tokudb-7.0.1"
COMP_CALL_INFO="CC='/usr/local/gcc-4.7/bin/gcc47'  CFLAGS='-Wall  -O3 -g -static-libgcc -fno-omit-frame-pointer -fno-strict-aliasing -DDBUG_OFF -DMY_PTHREAD_FASTMUTEX=1'  CXX='/usr/local/gcc-4.7/bin/g++47'  CXXFLAGS='-Wall  -Wno-unused-parameter -fno-implicit-templates -fno-exceptions -fno-rtti -O3 -g -static-libgcc -fno-omit-frame-pointer -fno-strict-aliasing -DDBUG_OFF -DMY_PTHREAD_FASTMUTEX=1'  LDFLAGS=''  ASFLAGS=''"
COMP_RUN_INFO="CC='/usr/local/gcc-4.7/bin/gcc47'  CFLAGS='-Wall  -O3 -g -static-libgcc -fno-omit-frame-pointer -fno-strict-aliasing -DDBUG_OFF -DMY_PTHREAD_FASTMUTEX=1'  CXX='/usr/local/gcc-4.7/bin/g++47'  CXXFLAGS='-Wall  -Wno-unused-parameter -fno-implicit-templates -fno-exceptions -fno-rtti -O3 -g -static-libgcc -fno-omit-frame-pointer -fno-strict-aliasing -DDBUG_OFF -DMY_PTHREAD_FASTMUTEX=1'  LDFLAGS=''  ASFLAGS=''"

grep -A 5 '^VERSION' mariadb-5.5.31-linux-x86_64/bin/mysqlbug
VERSION="5.5.31"
COMP_CALL_INFO="CC='/usr/bin/gcc'  CFLAGS='-Wall  -O3 -g -static-libgcc -fno-omit-frame-pointer -fno-strict-aliasing -DDBUG_OFF -DMY_PTHREAD_FASTMUTEX=1'  CXX='/usr/bin/c++'  CXXFLAGS='-Wall  -Wno-unused-parameter -fno-implicit-templates -fno-exceptions -fno-rtti -O3 -g -static-libgcc -fno-omit-frame-pointer -fno-strict-aliasing -DDBUG_OFF -DMY_PTHREAD_FASTMUTEX=1'  LDFLAGS=''  ASFLAGS=''"
COMP_RUN_INFO="CC='/usr/bin/gcc'  CFLAGS='-Wall  -O3 -g -static-libgcc -fno-omit-frame-pointer -fno-strict-aliasing -DDBUG_OFF -DMY_PTHREAD_FASTMUTEX=1'  CXX='/usr/bin/c++'  CXXFLAGS='-Wall  -Wno-unused-parameter -fno-implicit-templates -fno-exceptions -fno-rtti -O3 -g -static-libgcc -fno-omit-frame-pointer -fno-strict-aliasing -DDBUG_OFF -DMY_PTHREAD_FASTMUTEX=1'  LDFLAGS=''  ASFLAGS=''"

**Comment by prohaska** [comment]
we build with gcc 4.7.  with this compiler, handler socket gets a dependency on libstdc++.so.6.0.17, which is built when gcc 4.7 is built.

**Comment by thatsafunnyname** [comment]
Thanks.  Leif commented in https://groups.google.com/d/msg/tokudb-user/TB6DZDVCq-g/lNvQ2kdbtP8J adding background.  I ended up building gcc 4.7.2 with libstdc++.so\* from src (using http://joelinoff.com/blog/?p=811 but also see http://www.gnu.org/software/gsrc/ and http://gcc.gnu.org/wiki/InstallingGCC for anyone else wanting to do the same) and setting LD_LIBRARY_PATH in support-files/mysql.server to get the handlersocket plugin to install on RHEL6.

**Comment by alexeyz** [comment]
Easiest thing to do is install the default MariaDB 5.5.x rpm's for RHEL6/CentOs6 using the mariadb.org repo.  That should get you all the dependencies you need to get TokuDB going.

**Comment by thatsafunnyname** [comment]
Thanks.
It looks like TokuDB included in MariaDB 5.5 from mariadb.org is currently targeting 5.5.33 - https://mariadb.atlassian.net/browse/MDEV/fixforversion/13300
https://mariadb.atlassian.net/browse/MDEV-4507
  https://mariadb.atlassian.net/browse/MDEV-4532
  https://mariadb.atlassian.net/browse/MDEV-4533
I am looking forward to having TokuDB included in the mariadb.org distributions.

**Comment by alexeyz** [comment]
It would be great if it was in 5.5.33 but I'm not going to put too much hope on it.  It was targeted for 5.5.32 if you look at the History here:  https://mariadb.atlassian.net/browse/MDEV-4507

Keeping my fingers crossed though...

Please vote on that issue btw.

**Comment by thatsafunnyname** [comment]
You can try it in 5.5.33
  https://mariadb.atlassian.net/browse/MDEV-4507
  http://bazaar.launchpad.net/~maria-captains/maria/5.5/revision/3888

**Comment by alexeyz** [comment]
You know we're just passing the same link back and forth? :) 5.5.33 hasn't been released yet, have to wait. :+1:

**Comment by thatsafunnyname** [comment]
alexeyz, I have a new link to pass:
  https://mariadb.atlassian.net/browse/MDEV-5027
I will close this issue in favour of MDEV-5027 as it seems likely now that MariaDB includes TokuDB, that the build and package changes required will be worked on in MDEV-5027

**Comment by leifwalsh** [comment]
@thatsafunnyname I don't have an atlassian account, so can you add a note to MDEV-5027 linking back to this ticket, to give the maria folk some context and the information we have so far?

**Comment by thatsafunnyname** [comment]
@leifwalsh MDEV-5027 already had a link to the thread on the tokudb-user mailing list, and in particular your post with details.  I added a link in MDEV-5027 back to this ticket.

**Comment by leifwalsh** [comment]
Thanks. 

## 

Cheers,
Leif
