### ISSUE TITLE
Checksum failure while reading node partition in file

### ISSUE THREAD

**Issue by fimbulvetr** [Tokutek/mariadb-5.5#75]
It appears this was caused while running a query:

Checksum failure while reading node partition in file ./_file_sql_95631_1e_key_indexname_1c3623b5e_3_19.tokudb.
150421 18:52:37 [ERROR] mysqld got signal 6 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.

To report this bug, see http://kb.askmonty.org/en/reporting-bugs

We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed, 
something is definitely wrong and this may fail.

Server version: 5.5.41-tokudb-7.5.5-MariaDB-log
key_buffer_size=16777216
read_buffer_size=262144
max_used_connections=30
max_threads=302
thread_count=19
It is possible that mysqld could use up to 
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 7521021 K  bytes of memory
Hope that's ok; if not, decrease some variables in the equation.

Thread pointer: 0x0x0
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
stack_bottom = 0x0 thread_stack 0x48000
(my_addr_resolve failure: fork)
/vol/mysql/bin/mysqld(my_print_stacktrace+0x2b) [0xab4a0b]
/vol/mysql/bin/mysqld(handle_fatal_signal+0x398) [0x6d1138]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10340) [0x7f198befe340]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x39) [0x7f198b555cc9]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148) [0x7f198b5590d8]
/vol/mysql/lib/plugin/ha_tokudb.so(toku_ftnode_pf_callback(void_, void_, void_, int, pair_attr_s_)+0xaad) [0x7f1945d3098d]
/vol/mysql/lib/plugin/ha_tokudb.so(toku_cachetable_pf_pinned_pair(void_, int (_)(void_, void_, void_, int, pair_attr_s_), void_, cachefile_, blocknum_s, unsigned int)+0x10c) [0x7f1945d05dac]
/vol/mysql/lib/plugin/ha_tokudb.so(toku_ftnode_cleaner_callback(void_, blocknum_s, unsigned int, void_)+0x7c) [0x7f1945cf002c]
/vol/mysql/lib/plugin/ha_tokudb.so(cleaner::run_cleaner()+0x273) [0x7f1945d02013]
/vol/mysql/lib/plugin/ha_tokudb.so(+0xc153e) [0x7f1945cd253e]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8182) [0x7f198bef6182]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f198b61947d]
The manual page at http://dev.mysql.com/doc/mysql/en/crashing.html contains
information that should help you find out what is causing the crash.
150421 18:52:43 mysqld_safe Number of processes running now: 0

This was a recent upgrade (within the last week, some millions of querys to this and other indexes/tables since then) from 5.5.39-tokudb-7.5.2-MariaDB-log

**Comment by prohaska7** [comment]
Please move this issue to the tokudb-user community google group or the Tokutek JIRA  bug tracking system.
