### ISSUE TITLE
check table does not update progress

### ISSUE THREAD

**Issue by prohaska** [Tokutek/mariadb-5.5#8]
| Id  | User      | Host      | db             | Command | Time | State                                       | Info               | Progress |
| 489 | tokubuild | localhost | tpch30G_tokudb | Query   |  101 | ./tpch30G_tokudb/orders key=orders_dt_idx 2 | check table orders |    0.000 |

**Comment by tmcallaghan** [comment]
Moved to Jira as https://tokutek.atlassian.net/browse/DB-576
